import { Router, Request, Response } from 'express';

const router = Router();

const ABU_DHABI_PLACES = [
  {
    id: 'szgm',
    name: 'Sheikh Zayed Grand Mosque',
    nameAr: 'جامع الشيخ زايد الكبير',
    category: 'Cultural & Heritage',
    categoryAr: 'ثقافة وتراث',
    lat: 24.4128,
    lng: 54.4750,
    distanceKm: 8.4,
    walkingTimeMins: 95,
    cyclingTimeMins: 26,
    shadeCoveragePercent: 85,
    heatSafetyLevel: 'Air-Conditioned Corridors & Reflective Courtyards',
    accessibility: '100% Wheelchair & Stroller Accessible with Electric Golf Carts',
    sustainableTransit: 'Abu Dhabi Bus Route 94 (Direct air-conditioned bus stop at entrance)',
    description: 'An architectural masterpiece of Islamic heritage, world tolerance, and cultural dialogue featuring 82 white marble domes and shaded arcades.',
    heritageNote: 'Traditional Islamic stone carving, water mirror cooling courtyards inspired by historical Moorish architecture.',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw6vvobgr9gJLCc_q9DGPDZcHWxhpT8Fh2Wk9Jx88PSw&s=10',
    tags: ['Iconic', 'Culture', 'Air-Conditioned Indoor', 'POD Friendly']
  },
  {
    id: 'qaw',
    name: 'Qasr Al Watan',
    nameAr: 'قصر الوطن',
    category: 'Heritage & Governance',
    categoryAr: 'تراث وحوكمة',
    lat: 24.4623,
    lng: 54.3168,
    distanceKm: 6.2,
    walkingTimeMins: 72,
    cyclingTimeMins: 20,
    shadeCoveragePercent: 90,
    heatSafetyLevel: 'Indoor Palace Sanctuary & Shaded Gardens',
    accessibility: 'Step-free routes, accessible ramps, Braille guides available',
    sustainableTransit: 'Bus Route 034 & 067 to Ras Al Akhdar',
    description: 'The UAE Presidential Palace celebrating Emirati governance, Arabian calligraphy, and historic craftsmanship.',
    heritageNote: 'Showcases Arabic geometry, regional scholarship, and the historic diplomacy of the UAE founders.',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT99l1a3eBJ2Dy2xkn8wEDSh0quh3NqeZFSJaJiusGe9A&s=10',
    tags: ['Heritage', 'Presidential', 'Indoor Cool', 'Accessible']
  },
  {
    id: 'corniche',
    name: 'Abu Dhabi Corniche',
    nameAr: 'كورنيش أبوظبي',
    category: 'Coastal Walking & Cycling',
    categoryAr: 'ممشى ومسار دراجات ساحلي',
    lat: 24.4715,
    lng: 54.3412,
    distanceKm: 4.1,
    walkingTimeMins: 45,
    cyclingTimeMins: 14,
    shadeCoveragePercent: 78,
    heatSafetyLevel: 'Date Palm Canopy & Sea Breeze Zone (Best early morning or sunset)',
    accessibility: 'Fully paved, ramped beach crossings, tactile ground indicators',
    sustainableTransit: 'Corniche Dedicated Cycle Highway & Bus Routes 005, 032, 063',
    description: '8 kilometers of pristine waterfront featuring segregated pedestrian and cycling lanes, shaded gazebos, and blue-flag beaches.',
    heritageNote: 'Abu Dhabi maritime history and traditional dhow harbor heritage.',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEn1cnbyCQ2b3o5g0110T0Zvg1nyRK706efgbPWbH7Hg&s=10',
    tags: ['Cycling Track', 'Sea Breeze', 'Date Palms', 'Family Friendly']
  },
  {
    id: 'saadiyat',
    name: 'Saadiyat Cultural District (Louvre AD)',
    nameAr: 'منطقة السعديات الثقافية (متحف اللوفر أبوظبي)',
    category: 'Culture & Nature',
    categoryAr: 'ثقافة وطبيعة',
    lat: 24.5312,
    lng: 54.4367,
    distanceKm: 7.8,
    walkingTimeMins: 88,
    cyclingTimeMins: 24,
    shadeCoveragePercent: 92,
    heatSafetyLevel: 'Iconic "Rain of Light" Passive Cooling Dome',
    accessibility: 'Full mobility accessibility, elevators, complimentary wheelchairs',
    sustainableTransit: 'Cultural Express Bus Route & Saadiyat Green Shuttles',
    description: 'Home to Louvre Abu Dhabi, Zayed National Museum, and Guggenheim Abu Dhabi with passive cooling microclimates.',
    heritageNote: 'Inspired by traditional Emirati falaj water systems and palm oasis shade patterns.',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaeNn81_UbaHZNuK14Xifbx6f29IU52Gj2e-vLV6nLqQ&s=10',
    tags: ['Museum', 'Passive Cooling', 'Culture', 'Eco Architecture']
  },
  {
    id: 'mangroves',
    name: 'Mangrove National Park',
    nameAr: 'منتزه قرم الجبيل الوطني',
    category: 'Ecological & Nature Sanctuary',
    categoryAr: 'محمية طبيعية بيئية',
    lat: 24.4552,
    lng: 54.4190,
    distanceKm: 5.3,
    walkingTimeMins: 60,
    cyclingTimeMins: 18,
    shadeCoveragePercent: 70,
    heatSafetyLevel: 'Natural Microclimate with Marine Evaporative Cooling',
    accessibility: 'Raised wooden boardwalks suitable for wheelchairs & strollers',
    sustainableTransit: 'Eastern Mangroves Bus Stop Route 056 & Solar Kayaks',
    description: '75% of UAE mangrove forests protecting biodiversity, blue carbon sequestration, and coastal marine life.',
    heritageNote: 'Traditional Emirati coastal preservation and sustainable fishing history.',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBOnaBML0TDrkL92qC95r2S4LV487UGkcHo4MGLEEHpg&s=10',
    tags: ['Eco Sanctuary', 'Blue Carbon', 'Boardwalk', 'Zero Emission']
  },
  {
    id: 'masdar',
    name: 'Masdar City Eco-District',
    nameAr: 'مدينة مصدر المستدامة',
    category: 'Net-Zero Innovation',
    categoryAr: 'ابتكار الحياد المناخي',
    lat: 24.4329,
    lng: 54.6171,
    distanceKm: 14.2,
    walkingTimeMins: 140,
    cyclingTimeMins: 42,
    shadeCoveragePercent: 95,
    heatSafetyLevel: 'Traditional Wind Tower (Barjeel) Channelling Cooler Air',
    accessibility: '100% barrier-free pedestrian streets and autonomous transit pods',
    sustainableTransit: 'Autonomous PRT (Personal Rapid Transit) & Masdar Bus Hub',
    description: 'Pioneering clean-tech urban community with narrow shaded alleys that lower ambient temperature by up to 10°C.',
    heritageNote: 'Modern rebirth of ancient Arab desert windcatchers (Barjeel) and compact urban shading.',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmU1hd3DZO-56t7gStJIdcZDqbyuSPsVqW-0rFn18hGA&s=10',
    tags: ['Net-Zero', 'Wind Tower', 'Autonomous Transit', 'Innovation']
  },
  {
    id: 'yas',
    name: 'Yas Island Cycling & Entertainment',
    nameAr: 'جزيرة ياس ومسار الحلبة',
    category: 'Active Mobility & Entertainment',
    categoryAr: 'حركة نشطة وترفيه',
    lat: 24.4926,
    lng: 54.6067,
    distanceKm: 16.5,
    walkingTimeMins: 180,
    cyclingTimeMins: 48,
    shadeCoveragePercent: 65,
    heatSafetyLevel: 'Night Cycling Events & Shaded Hubs (TrainYAS evening sessions)',
    accessibility: 'Flat accessible corridors, Yas Express wheelchair lifts',
    sustainableTransit: 'Yas Express Electric Shuttles & Yas Marina Circuit Loop',
    description: 'World-class active mobility venue featuring Yas Marina Circuit community cycling, shaded promenades, and waterfront paths.',
    heritageNote: 'Modern entertainment balancing active fitness and UAE sports culture.',
    imageUrl: 'https://www.mediaoffice.abudhabi/assets/resized/sm/upload/xa/6y/a8/86/thumb-20220610_DCT_Yas-Island-attractions_Web-0-0-0-0.webp?k=20e6b0f9b0',
    tags: ['TrainYAS', 'Active Fitness', 'Evening Cycling', 'Connected']
  }
];

router.get('/', (req: Request, res: Response) => {
  res.json({
    success: true,
    count: ABU_DHABI_PLACES.length,
    data: ABU_DHABI_PLACES
  });
});

export default router;
